version: '3'
services:
  samba:
    container_name: samba
    hostname: samba
    image: sixeyed/samba
    volumes:
      - /home/roman/media:/mnt/media
      - /home/roman/nas:/mnt/nas
      - /home/roman/plex:/mnt/plex
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    command: samba.sh -s "media;/mnt/media;yes;no;yes;all" -s "nas;/mnt/nas;yes;no;yes;all" -s "plex;/mnt/plex;yes;no;y>    restart: always
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Moscow
      - PLEX_CLAIM=
      - PLEX_UID=1000
      - PLEX_GID=1000
    hostname: xxx
    volumes:
      - /home/roman/plex/SETUP/PLEX/database:/config
      - /home/roman/plex/SETUP/PLEX/transcode:/transcode
      - /home/roman/plex:/data
    #tmpfs: /transcode:uid=0
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=Transmission
      - PASS=4f92c19d05
    volumes:
      - /home/roman/plex/SETUP/TRANSMISSION/data:/config
      - /home/roman/plex/DOWNLOADS:/downloads
      - /home/roman/plex/SETUP/TRANSMISSION/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
