version: '3'
services:
  traefik:
      image: "traefik:latest"
      container_name: "traefik"
      restart: always
      networks:
        - default
        - t1_proxy
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
      ports:
        - "80:80"
        - "443:443"
      labels:
        - "traefik.enable=true"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
        - "traefik.port=8080"
        - "traefik.docker.network=t1_proxy"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.SSLHost=example.com"
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
  #     - "traefik.frontend.headers.frameDeny: true" #customFrameOptionsValue overrides this
        - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"
        - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ${USERDIR}/setup/traefik:/etc/traefik
        - ${USERDIR}/setup/shared:/shared
networks:
  t1_proxy:
    external:
      name: t1_proxy
  default:
    driver: bridge
