version: '3'
services:
  samba:
    container_name: samba
    hostname: samba
    image: sixeyed/samba
    volumes:
      - /mnt/md0:/mnt/media
      - /home/roman:/mnt/server
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    command: samba.sh -s "media;/mnt/media;yes;no;yes;all" -s "server;/mnt/server;yes;no;yes;all"
    restart: always
