version: '3'
services:
  samba:
    container_name: samba
    hostname: samba
    image: dperson/samba
    volumes:
      - /home/roman/nas:/mnt/nas
      - /home/roman/media:/mnt/media
    ports:
      - "139:139"
      - "445:445"
    command: samba.sh -s "nas;/mnt/nas;yes;no;yes;all" -s "media;/mnt/media;yes;no;yes;all" -p
    restart: always
