version: '3'
services:
  samba:
    container_name: samba
    hostname: samba
    image: dperson/samba
    volumes:
      - /home/roman/nas:/mnt/nas
      - /home/roman/media:/mnt/media
      - /home/roman/setup:/mnt/setup
    ports:
      - "139:139"
      - "445:445"
    command: samba.sh -s "nas;/mnt/nas;yes;no;yes;all" -s "media;/mnt/media;yes;no;yes;all" -s "setup;/mnt/setup;yes;no;yes;all" -p
    restart: always
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=transmission #optional
      - PASS=4f92c19d05 #optional
    volumes:
      - /home/roman/setup/transmission/config:/config
      - /home/roman/media/TORRENT:/downloads
      - /home/roman/setup/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /home/roman/setup/plex:/config
      - /home/roman/media/SERIALS:/tv
      - /home/roman/media/MOVIES:/movies
    restart: unless-stopped
