version: '3'
services:
  samba:
    container_name: samba
    hostname: samba
    image: sixeyed/samba
    volumes:
      - /home/roman/media:/mnt/media
      - /home/roman/nas:/mnt/nas
      - /home/roman/plex:/mnt/plex
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    command: samba.sh -s "media;/mnt/media;yes;no;yes;all" -s "nas;/mnt/nas;yes;no;yes;all" -s "plex;/mnt/plex;yes;no;y>    restart: always
    restart: always
